[황유정] flightlistview 기능 구현
wecode-bootcamp-korea/35-2nd-myhoneytrip-backend pull request #10
Opened 2022-08-08 04:17 UTC by xoxowo

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
-메인 페이지의 검색 결과 리스트 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 메인 페이지에서 출발지역, 도착지역, 출발일자, 돌아오는일자, 탑승객에 따른 검색 필터 구현 밑 검색 부분 프론트와 통신완료 확인,
2. query parameter string으로 사용
3. 페이지 네이션은 프론트와 상의 후 추후 수정가능성 있음 
4. select_related 사용하여 필터 구현 완료 
5. test 코드는 작성중입니다. ->오류 발생 중..

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 처음에 Q 필터를 사용하여 구현했으나 select_related를 사용해서 구현을하게됬습니다. 아직 필터 부분에서 테이블을 옮겨서 원하는 값을 가져오는게 어렵지만 지난번에 사용해보지 않았던 부분에 대해 조금 더 잘 알게된 것 같습니다...🥹

<br />

## :: 기타 질문 및 특이 사항
- 기존 페이지가 사라지는 페이지 네이션이 아닌 기존 리스트가 남아있고 추가로 페이지를 더 볼수 있게 해주는 '더보기' 기능을 구현하고싶은데 아직 어떻게 해야할지 잘 모르겠습니다..

2022-08-09 06:43 UTC, Kang-kyunghun requested changes

2022-08-09 06:43 UTC, Kang-kyunghun commented on flights/views.py
> +                            .filter(flight_route__airplane__airline__name__in=airlines).order_by(sort_options[sort_type])
1. filter를 2번 나눠서 사용한 이유가 있을까요?
2. front에서 받는 query paramete가 안 들어 올경우 filter 인자에 None이 들어갈텐데, 그러면 원하는 filtering이 안될 수 있습니다. filter에 들어가야하는 값이 반드시 필요한 값이라면, GET.get()이 아닌 대괄호("[]")을 이용하여, 값이 안 들어올 때 key error가 발생될 수 있게 해주세요.

2022-08-09 06:43 UTC, Kang-kyunghun commented on flights/tests.py
> +        )
데이터 생성 순서에 따라 테스트가 안 돌아 갈 수 있는데, 지금이 그 상황인 것 같습니다.

test 실행해서 잘 돌아가는지 확인해 주시고, 만약 실패 한다면 수정해 주세요.

2022-08-09 13:53 UTC, xoxowo commented on flights/views.py
> +                            .filter(flight_route__airplane__airline__name__in=airlines).order_by(sort_options[sort_type])
1. 다시 확인해보니 굳이 나눌 필요가 없었네요! 확인 후 수정했습니다.
2. 필수로 받아야하는 값은 ("[]") 처리하였고 key error 발생하게끔 수정했습니다.

2022-08-10 01:03 UTC, xoxowo commented on flights/tests.py
> +        )
생성 순서는 수정했는데 다른 오류가 발생해서 확인 중입니다...

2022-08-10 08:52 UTC, merged

2022-08-10 08:52 UTC, Kang-kyunghun commented
LGTM