[Myhoneytrip] Created Reservation view
wecode-bootcamp-korea/35-2nd-myhoneytrip-backend pull request #3
Opened 2022-08-04 13:39 UTC by AhnSang0915

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ x] 기능 추가
<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 예약 페이지 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 예약페이지 데이터 입력 API구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- Frontend 데이터를 데이터 베이스에 입력할 수 있게끔 변경하는 로직을 작성함

<br />

## :: 기타 질문 및 특이 사항
- ReservationView 에서 transaction을 사용해 에러 발생시에도 Booking.objects.create함수에서 데이터 생성이 되는 현상을 막으려 했는데 에러가 발생해도 데이터가 그대로 들어갑니다. @transaction.atomic()을 사용한 부분에 대해 리뷰를 받고 싶습니다 .

2022-08-05 06:16 UTC, Kang-kyunghun requested changes

2022-08-05 06:16 UTC, Kang-kyunghun commented on bookings/views.py
> +from users.models    import User
```suggestion
from uuid import uuid4

from django.db    import transaction
from django.http  import JsonResponse
from django.views import View

from bookings.models import Booking, BookingStatus, Passenger
from users.models    import User
```

2022-08-05 06:16 UTC, Kang-kyunghun commented on bookings/views.py
> +
공백은 1칸으로 해주세요.

2022-08-05 06:16 UTC, Kang-kyunghun commented on bookings/views.py
> +            )
1. booking_status의 id 1번이 어떤 상태인지 어떻게 알 수 있을까요? 이렇게 단순히 id 값을 하드코딩하면 다른 사람이 파악하기도 어렵고, 데이터베이의 값이 바뀌게 되면 코드를 전체적으로 수정해야 되는 상황이 생깁니다.
2. User도 마찬가지 입니다. 데코레이터를 통해 얻는 user 정보를 사용해 주세요.
3. uuid4() 바로 사용하면 저희가 원하는 데이터 타입이 아닐 것입니다. 우리가 원하는 데이터 타입으로 바꾸는 작업이 필요합니다.

2022-08-05 06:16 UTC, Kang-kyunghun commented on bookings/views.py
> +                booking_id = booking.id)for i in range(len(passengers))]
1. passengers의 정보가 어떻게 들어오나요? 아래와 같이 리스트 안에 승객 한 명당 정보를 dictionary로 받으면 좋을 것 같습니다.
```python
passengers = [{},{}.{}]
```
2. 코드를 조금 정리하면 다음과 같이 수정 할 수 있을 것 같아요.
```suggestion
            passengers = data['passengers']

            passenger_list = [Passenger(
                first_name = passenger['first_name'],
                last_name  = passenger['last_name'],
                gender     = passenger['gender'],
                birthday = f'{passenger['year']}-{passenger['month']}-{passenger['day']}',
                booking_id = booking.id
            )for passenger in passengers]
            Passenger.objects.bulk_create(passenger_list)
```

2022-08-05 06:16 UTC, Kang-kyunghun commented on flights/migrations/0004_rename_airpalne_flightroute_airplane.py
> +# Generated by Django 4.0.6 on 2022-08-03 23:00
DB 수정 사항은 따로 올려 주셔야 합니다.
그렇지 않으면 해당 PR이 merge 될 때까지 DB 반영이 안 됩니다.

2022-08-05 13:19 UTC, AhnSang0915 commented on bookings/views.py
> +
수정 했습니다!

2022-08-05 13:19 UTC, AhnSang0915 commented on bookings/views.py
> +            )
Enum 클래스 지정해서 core앱에 넣어서 사용하는거 맞나요? 일단 그렇게 코드 작성 했습니다.

2022-08-05 13:20 UTC, AhnSang0915 commented on bookings/views.py
> +                booking_id = booking.id)for i in range(len(passengers))]
받는 데이터 수정후 코드에 반영 했습니다.

2022-08-09 09:14 UTC, Kang-kyunghun requested changes

2022-08-09 09:14 UTC, Kang-kyunghun commented on bookings/urls.py
> +]
```suggestion
urlpatterns = [
    path('', BookingView.as_view())
]
```

2022-08-09 09:14 UTC, Kang-kyunghun commented on core/utils.py
> +    CANCELED = 3
```suggestion
    UPCOMING = 1
    LAST     = 2
    CANCELED = 3
```

2022-08-09 09:14 UTC, Kang-kyunghun commented on core/utils.py
> +    CANCELED = 2
```suggestion
    CONFIRM  = 1
    CANCELED = 2
```

2022-08-09 09:14 UTC, Kang-kyunghun commented on bookings/views.py
> +                user = request.user
```suggestion
                data = json.loads(request.body)
                user = request.user
```

2022-08-09 09:14 UTC, Kang-kyunghun commented on bookings/views.py
> +                flight_details = data['flight_detail_id']
```suggestion
                passengers     = data['passengers']
                flight_details = data['flight_detail_id']
```

2022-08-09 09:14 UTC, Kang-kyunghun commented on bookings/views.py
> +                ticket_confirm = TicketStatusEnum.CONFIRM.value
```suggestion
                upcoming       = BookingStatusEnum.UPCOMING.value
                ticket_confirm = TicketStatusEnum.CONFIRM.value
```

2022-08-09 09:15 UTC, Kang-kyunghun commented
간단한 수정 사항 있습니다.

그리고 model 바뀌면 코드도 바뀔 것 같으니 모델 바뀐 뒤에 더 리뷰 하겠습니다.

2022-08-11 01:32 UTC, Kang-kyunghun commented
LGTM

2022-08-11 01:32 UTC, merged