Feature/kakao social login
wecode-bootcamp-korea/35-2nd-myhoneytrip-backend pull request #4
Opened 2022-08-04 13:58 UTC by J-EUM

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 로그인api이용한 소셜 로그인 구

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 카카오 회원가입 로그인
- 요청으로 들어온 카카오 인가코드로 카카오 토큰을 받는다.
- 카카오 토큰으로 카카오 유저정보를 확인한다.
- 우리 서버의 유저 정보와 비교해서 회원이 아니면 회원가입후 로그인(토큰발급)
- 회원이면 바로 로그인

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- requests이용해서 다른 서버에 요청 보내는 법을 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항
- 예외처리.....어떻게 해야할까요

2022-08-05 06:01 UTC, Kang-kyunghun requested changes

2022-08-05 06:01 UTC, Kang-kyunghun commented on users/urls.py
> +    path('/signin', KakaoSignInView.as_view()),
지금은 일반 로그인이 없지만, 나중에 일반 로그인과 구별 될 수 있게 다음과 같이 수정하면 좋을 것 같아요.
```suggestion
    path('/signin/kakao', KakaoSignInView.as_view()),
```

2022-08-05 06:01 UTC, Kang-kyunghun commented on users/views.py
> +from .models import User
```suggestion
import json

import requests
import jwt
from django.http  import JsonResponse
from django.views import View
from django.conf  import settings

from .models import User
```

2022-08-05 06:01 UTC, Kang-kyunghun commented on users/views.py
> +        authorize_code = request.headers.get('Authorization', None)
auth_code는 body를 통해 받는 것이 좋을 것 같습니다.
Authorization이라는 헤더키로 받는 것은 조금 부적절한 것 같습니다.
아니면 적절한 헤더 키를 사용해 주세요.

2022-08-05 06:01 UTC, Kang-kyunghun commented on users/views.py
> +        redirect_uri   = 'http://localhost:3000/logining'
해당 정보는 my_settings.py로 옮겨 주세요.

2022-08-05 06:03 UTC, Kang-kyunghun commented
로직 자체는 잘 구성 되어 있는 것 같습니다.
현제 kakao와 관련된 코드들이 로직에 그대로 있는데, 해당 코드들은 따로 class를 만들어서 kakao완 관련된 것들만 모아 쓸수 있게 한 번 수정해 보세요.

2022-08-05 06:53 UTC, J-EUM commented on users/urls.py
> +    path('/signin', KakaoSignInView.as_view()),
넵

2022-08-05 06:54 UTC, J-EUM commented on users/views.py
> +        authorize_code = request.headers.get('Authorization', None)
네 authorization은 우리서버에서 인가 받을때 사용하는건가요?

2022-08-05 06:55 UTC, J-EUM commented on users/views.py
> +        redirect_uri   = 'http://localhost:3000/logining'
넵

2022-08-10 06:33 UTC, Kang-kyunghun commented
LGTM~~!

2022-08-10 06:34 UTC, merged